apiVersion: batch/v1
kind: CronJob
metadata:
  name: informant
spec:
  # Replaced by kustomize from `informant-config.data.CRON`.
  schedule: "0 * * * *"
  # Replaced by kustomize from `informant-config.data.TZ`.
  timeZone: America/Fortaleza
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: informant
              image: ghcr.io/nayetdet/informant:latest
              imagePullPolicy: Always
              env:
                - name: TZ
                  valueFrom:
                    configMapKeyRef:
                      name: informant-config
                      key: TZ
                - name: TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: informant-secret
                      key: TELEGRAM_BOT_TOKEN
                - name: TELEGRAM_BOT_CHAT_ID
                  valueFrom:
                    secretKeyRef:
                      name: informant-secret
                      key: TELEGRAM_BOT_CHAT_ID
              volumeMounts:
                - name: informant-data
                  mountPath: /root/.codex
                  subPath: .codex
                - name: informant-data
                  mountPath: /app/data
                  subPath: data
          volumes:
            - name: informant-data
              persistentVolumeClaim:
                claimName: informant-pvc
